### ISSUE TITLE
build and submit to Pypi

### ISSUE THREAD

**Issue by javasoze** [dashbase/dashbase-tools#16]

**Comment by PureWhiteWu** [comment]
Do we need to make this use git-flow like cli? All commits merge into develop, and when we merge into master then we automatically build and submit to pypi using ci?

**Comment by PureWhiteWu** [comment]
- [ ] add a default "develop" branch
- [ ] automatically build and submit to pypi on ci

**Comment by javasoze** [comment]
use docker instead, no need to do this.
