### ISSUE TITLE
update document for fuse

### ISSUE THREAD

**Issue by PureWhiteWu** [dashbase/dashbase-tools#31]
This shuold be run in background mode, which means we should add `&` after the command.
But there's no `&` in README.md, which may make users run the command and feel that it's stuck.
Also, the hint in the script should be updated too.

Besides, we should write a more clearly document to tell the users these things:
- [x] what is fuse
- [ ] what can dashbase-fuse do
- [x] how to install dashbase-fuse & pre-requirements (osxfuse on mac, fuse libfuse2 using apt-get, fuse-devel fuse-lib using yum)
- [ ] what does dashbase-mnt do
- [x] sample usage & screenshots or asciinema

**Comment by javasoze** [comment]
Please add it here:

https://github.com/dashbase/dashbase-tools/wiki/Dashbase-Mounted-as-a-File-System

**Comment by PureWhiteWu** [comment]
okay. docker privileged is not enough, will need another option. i will add it later.

**Comment by PureWhiteWu** [comment]
I've tested, --privileged works well, maybe i misconfigured something last time.
