### ISSUE TITLE
docker does not support fuse normally

### ISSUE THREAD

**Issue by PureWhiteWu** [dashbase/dashbase-tools#47]
we should write this in document

**Comment by PureWhiteWu** [comment]
https://github.com/moby/moby/issues/514

**Comment by PureWhiteWu** [comment]
https://github.com/moby/moby/issues/9448

**Comment by javasoze** [comment]
we are not exposing this functionality externally until we feel it is ready. In the meantime, let's add documentation in the wiki: https://github.com/dashbase/dashbase-tools/wiki/Dashbase-Mounted-as-a-File-System
