### ISSUE TITLE
defaults for logtail/dtail tool

### ISSUE THREAD

**Issue by javasoze** [dashbase/dashbase-tools#87]
All the various options makes logtail very cumbersome to use. Instead we should follow the pattern for the aws tool, .e.g. have a file, e.g. ```~/.dashbase/config``` that has default settings for

* host (-a option)
* table name (table part of the -a option, or -t option)
* number of results to return (-n option)
* fields (-f option)

flow:

*  if these options are not set on the command line, read from  ```~/.dashbase/config```, if the file does not exist, output an error.
*  if ```~/.dashbase/config``` does not exist, take the option read from command line and create the file with the configs so subsequent runs can work without these options
* if ```~/.dashbase/config``` exists, and the option is set on the command line, use provided option, but do not overwrite the config file

**Comment by WPH95** [comment]
> if ~/.dashbase/config does not exist, take the option read from command line and create the file with the configs so subsequent runs can work without these options

i think we should not to create the config file in first time, just use default
