### ISSUE TITLE
create a pex file 

### ISSUE THREAD

**Issue by javasoze** [dashbase/dashbase-tools#9]

**Comment by PureWhiteWu** [comment]
I would do these things:
- [ ] write scripts to automatically build pex file (in "hack" folder like docker)
- [ ] write sciprts to automatically upload to s3 bucket (same above)
- [ ] write document for how to build pex file and upload to s3 bucket
- [ ] automatically build pex file using the scripts to build pex file and upload to s3 bucket in ci when we release new versions

**Comment by keitaf** [comment]
Or can we build a docker image for tools? So that we can run tools by doing something like
```
docker run dashbase/logtail -a ADDR ....
```

Since dashbase-tools doesn't require any storage, it should be easy to docker-nize the tool.

**Comment by PureWhiteWu** [comment]
good idea! #22 @keitaf

**Comment by javasoze** [comment]
Agree with @keitaf , closing this.
